[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.12.0"
  NPM_VERSION = "10.5.0"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects untuk mendukung routing SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 