[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.12.0"
  NPM_VERSION = "10.5.0"
  # Paksa penggunaan npm (bukan pnpm)
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects untuk Next.js routing
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Fallback untuk SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 