[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "20.12.0"
  NPM_VERSION = "10.5.0"
  USE_NPM_INSTALL = "true"
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Hapus redirects SPA karena Next.js menggunakan sistem routing sendiri
# dan plugin @netlify/plugin-nextjs sudah menangani ini 