[build]
  publish = "out"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_PUBLIC_EMAILJS_SERVICE_ID = "service_5mk1t2z"
  NEXT_PUBLIC_EMAILJS_TEMPLATE_ID = "template_yj3blyg"
  NEXT_PUBLIC_EMAILJS_USER_ID = "WrdMD5erXU1TjP0SR"
  # Fix untuk masalah Next.js App Router
  NEXT_PRIVATE_TARGET = "server"
  # Tidak menggunakan i18n di App Router
  NEXT_PUBLIC_DISABLE_I18N = "true"

# Pengaturan header untuk file PDF.js worker dan resource
[[headers]]
  for = "/pdf.worker*.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000"

# Pengaturan header untuk font dan asset statis
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Pengaturan header untuk file PDF dan dokumen
[[headers]]
  for = "/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "inline"
    Cache-Control = "public, max-age=604800"

# Pengaturan redirect khusus Next.js
# Pertama, tangani asset statis
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Tangani file-file di root
[[redirects]]
  from = "/pdf.worker.min.js"
  to = "/pdf.worker.min.js"
  status = 200
  force = true

[[redirects]]
  from = "/pdf-worker-fallback.js"
  to = "/pdf-worker-fallback.js"
  status = 200
  force = true

[[redirects]]
  from = "/promise-polyfill.js"
  to = "/promise-polyfill.js"
  status = 200
  force = true

# API routes harus ditangani dengan 404 karena Next.js static export tidak mendukung API
[[redirects]]
  from = "/api/*"
  to = "/404.html"
  status = 404

# Semua halaman lain harus dikembalikan ke index.html secara default (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Info situs
[Settings]
  ID = "02a6fa83-7aa8-4d12-9d14-db7279b92914"
  Name = "musical-souffle-ad6848"

# Plugin nextjs
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Integrasi dengan GitHub Actions
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Cache Control
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()" 