"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"
import { 
  Language, 
  TranslationKeys, 
  TranslationsType, 
  LanguageNames 
} from "@/types/translations"
import { mergeTranslations, additionalTranslations } from "@/utils/translations"

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
  getAllLanguages: () => { code: Language; name: string }[]
  changeLanguage: (lang: Language) => void
  mounted: boolean
}

// Daftar nama bahasa untuk UI selector
const languageNames: LanguageNames = {
  en: "English",
  id: "Bahasa Indonesia",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  zh: "中文",
  ja: "日本語",
  ko: "한국어",
  ar: "العربية"
}

// Terjemahan dalam berbagai bahasa
const baseTranslations: TranslationsType = {
  en: {
    "hero.title": "IT & Cyber Security Enthusiast",
    "hero.subtitle": "Specialized in System Security, Linux Administration & Network Protection",
    "hero.cta": "Get Started",
    "services.title": "What I Do",
    "services.subtitle": "Specialized expertise and professional services",
    "services.uiux.title": "UI/UX Design",
    "services.uiux.description": "Crafting intuitive user interfaces and seamless user experiences for digital products.",
    "services.digitalMarketing.title": "Digital Marketing",
    "services.digitalMarketing.description": "Strategic marketing solutions to boost your online presence and reach.",
    "services.performance.title": "Performance Optimization",
    "services.performance.description": "Speed up your digital platforms for better user experience and SEO.",
    "services.security.title": "Cybersecurity",
    "services.security.description": "Implementing robust security measures to protect digital assets and sensitive information.",
    "portfolio.title": "My Portfolio",
    "portfolio.subtitle": "Pioneering advanced solutions at the convergence of IT, Linux systems, and cybersecurity architecture – where technical excellence meets visionary innovation and strategic growth",
    "portfolio.search": "Search projects...",
    "portfolio.filter.all": "All",
    "portfolio.viewDetails": "View Details",
    "portfolio.viewProject": "View Project",
    "portfolio.liveDemo": "Live Demo",
    "portfolio.projectOverview": "Project Overview",
    "portfolio.keyFeatures": "Key Features",
    "portfolio.projectDetails": "Project Details",
    "portfolio.client": "Client",
    "portfolio.date": "Date",
    "portfolio.technologies": "Technologies",
    "portfolio.resetFilters": "Reset Filters",
    "portfolio.noProjectsMatch": "No projects match your filters.",
    "portfolio.filterByTags": "Filter by tags",
    "portfolio.allTags": "All Tags",
    "portfolio.selectTagsToFilter": "Select tags to filter projects",
    "portfolio.clearFilters": "Clear filters",
    "portfolio.moreTags": "+{0} more",
    "certifications.title": "My Certifications",
    "certifications.subtitle": "Professional certificates and achievements in cybersecurity and related fields",
    "certifications.viewDetails": "View Details",
    "certifications.openPdf": "Open PDF",
    "certifications.description": "Description",
    "certifications.competencies": "Key Competencies",
    "certifications.competency1": "Understanding security principles and best practices",
    "certifications.competency2": "Identifying and mitigating security vulnerabilities",
    "certifications.competency3": "Implementing security controls and technologies",
    "certifications.competency4": "Responding to security incidents and threats",
    "certifications.details": "Certificate Details",
    "certifications.issuedBy": "Issued By",
    "certifications.date": "Issue Date",
    "certifications.category": "Category",
    "certifications.expertise": "Areas of Expertise",
    "certifications.searchPlaceholder": "Search certifications...",
    "certifications.all": "All",
    "certifications.noMatch": "No certifications match your filters",
    "certifications.resetFilters": "Reset Filters",
    "certifications.quickLinks": "Quick Links",
    "certifications.latest": "Latest Certificates",
    "certifications.popular": "Popular Certificates",
    "certifications.filterByTags": "Filter by tags",
    "certifications.allTags": "All Tags",
    "certifications.selectTagsToFilter": "Select tags to filter certifications",
    "certifications.clearFilters": "Clear filters",
    "certifications.moreTags": "+{0} more",
    "skills.title": "Skills Analysis",
    "skills.subtitle": "Comprehensive visualization of technical expertise and professional growth",
    "skills.chart.radarView": "Radar View",
    "skills.chart.barView": "Bar View",
    "skills.chart.progressView": "Progress View",
    "skills.linux": "Linux Admin",
    "skills.linux.description": "Installation, configuration, and management of Linux systems",
    "skills.security": "System Security",
    "skills.security.description": "Implementation of security measures and protocols",
    "skills.virtualization": "Virtualization",
    "skills.virtualization.description": "Setup and management of virtual environments",
    "skills.scripting": "Shell Scripting",
    "skills.scripting.description": "Automation of tasks through shell scripts",
    "skills.documentation": "Documentation",
    "skills.documentation.description": "Creation of comprehensive technical documentation",
    "skills.problemSolving": "Problem Solving",
    "skills.problemSolving.description": "Analytical approach to technical challenges",
    "skills.development.title": "Web Development",
    "skills.development.description": "Building responsive and interactive web applications using modern frameworks and technologies.",
    "skills.design.title": "Web Design",
    "skills.design.description": "Creating visually appealing and user-friendly interfaces with a focus on user experience.",
    "skills.consulting.title": "IT Consulting",
    "skills.consulting.description": "Providing expert advice on technology solutions, system architecture, and digital transformation.",
    "contact.title": "Get in Touch",
    "contact.subtitle": "Let's discuss how we can help your business grow",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.message": "Message",
    "contact.send": "Send Message",
    "contact.form.title": "Send Message",
    "contact.form.description": "Fill out the form below to send a message via email or WhatsApp.",
    "contact.form.name": "Name",
    "contact.form.namePlaceholder": "Your name",
    "contact.form.email": "Email",
    "contact.form.emailPlaceholder": "your.email@example.com",
    "contact.form.subject": "Subject",
    "contact.form.subjectPlaceholder": "Topic of your message",
    "contact.form.message": "Message",
    "contact.form.messagePlaceholder": "Write your message here...",
    "contact.form.sending": "Sending...",
    "contact.form.whatsapp": "Send via WhatsApp",
    "contact.form.emailBtn": "Send Directly",
    "contact.form.emailClient": "Email Client",
    "contact.form.success": "Email Sent Successfully",
    "contact.form.error": "Failed to Send Email",
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.resume": "Resume",
    "nav.contact": "Contact",
    "nav.certifications": "Certifications",
    "language.selectLanguage": "Select Language",
    "certifications.viewCertificate": "View Certificate",
    "certifications.fileDetails": "File Information",
    "certifications.quickDetails": "Certificate Info",
    "certifications.close": "Close",
    "certifications.back": "Back",
    "achievements.title": "Professional Achievements",
    "achievements.subtitle": "Measurable results and milestones from my professional journey",
    "achievements.progress": "Progress",
    "achievements.moreDetails": "More Details",
    "achievements.lessDetails": "Less Details",
    "achievements.keyHighlights": "Key Highlights",
    "achievements.excellence.title": "Excellence in IT",
    "achievements.excellence.value": "5+",
    "achievements.excellence.description": "Years of continuous learning and professional development",
    "achievements.excellence.detail1": "Self-directed learning in Linux administration and system security",
    "achievements.excellence.detail2": "Completion of specialized online courses and workshops",
    "achievements.excellence.detail3": "Practical application of knowledge in professional settings",
    "achievements.excellence.detail4": "Consistent skill enhancement through hands-on projects",
    "achievements.optimization.title": "System Optimization",
    "achievements.optimization.value": "100%",
    "achievements.optimization.description": "Success rate in system administration and security implementation",
    "achievements.optimization.detail1": "Successful implementation of security protocols and measures",
    "achievements.optimization.detail2": "Optimization of system performance and resource utilization",
    "achievements.optimization.detail3": "Effective troubleshooting and problem resolution",
    "achievements.optimization.detail4": "Proactive maintenance and system monitoring",
    "achievements.efficiency.title": "Process Efficiency",
    "achievements.efficiency.value": "30%",
    "achievements.efficiency.description": "Average improvement in operational efficiency for clients",
    "achievements.efficiency.detail1": "Streamlining of workflows and operational processes",
    "achievements.efficiency.detail2": "Implementation of automation for routine tasks",
    "achievements.efficiency.detail3": "Reduction in system downtime and performance issues",
    "achievements.efficiency.detail4": "Enhanced productivity through optimized IT infrastructure",
    "achievements.delivery.title": "Project Delivery",
    "achievements.delivery.value": "100%",
    "achievements.delivery.description": "On-time completion rate for all assigned projects",
    "achievements.delivery.detail1": "Consistent adherence to project timelines and deadlines",
    "achievements.delivery.detail2": "Effective project planning and resource allocation",
    "achievements.delivery.detail3": "Clear communication and stakeholder management",
    "achievements.delivery.detail4": "Quality assurance and thorough testing before delivery",
    "growth.title": "Continuous Professional Growth",
    "growth.description": "My commitment to excellence is reflected in a consistent track record of achievement and growth. Through dedicated self-learning, practical application, and a passion for technology, I've developed a comprehensive skill set that enables me to deliver exceptional results.",
    "growth.lastUpdated": "Last updated: March 2025",
    "growth.successRate": "Success Rate",
    "growth.rateValue": "90%",
    "growth.quickNotes": "Professional Focus Areas",
    "resume.readyToCollaborate": "Ready to Collaborate?",
    "resume.collaborationText": "I'm always open to discussing new projects, opportunities, and collaborations.",
    "resume.contactMe": "Contact Me",
    "resume.downloadCV": "Download CV",
    "resume.downloading": "Downloading...",
    "resume.downloadSuccess": "Success!",
    "resume.downloadSuccessDesc": "Your CV has been downloaded successfully",
    "resume.downloadError": "Error",
    "resume.downloadErrorDesc": "Failed to download CV. Please try again later."
  },
  id: {
    "hero.title": "Praktisi IT & Keamanan Siber",
    "hero.subtitle": "Spesialis Keamanan Sistem, Administrasi Linux & Proteksi Jaringan",
    "hero.cta": "Mulai Sekarang",
    "services.title": "Apa yang Saya Lakukan",
    "services.subtitle": "Keahlian khusus dan layanan profesional",
    "services.uiux.title": "Desain UI/UX",
    "services.uiux.description": "Merancang antarmuka pengguna yang intuitif dan pengalaman pengguna yang lancar untuk produk digital.",
    "services.digitalMarketing.title": "Pemasaran Digital",
    "services.digitalMarketing.description": "Solusi pemasaran strategis untuk meningkatkan kehadiran online dan jangkauan Anda.",
    "services.performance.title": "Optimalisasi Kinerja",
    "services.performance.description": "Percepat platform digital Anda untuk pengalaman pengguna dan SEO yang lebih baik.",
    "services.security.title": "Keamanan Siber",
    "services.security.description": "Menerapkan langkah-langkah keamanan yang kuat untuk melindungi aset digital dan informasi sensitif.",
    "portfolio.title": "Portofolio Saya",
    "portfolio.subtitle": "Mempelopori solusi canggih di pertemuan IT, sistem Linux, dan arsitektur keamanan siber – tempat keunggulan teknis bertemu dengan inovasi visioner dan pertumbuhan strategis",
    "portfolio.search": "Cari proyek...",
    "portfolio.filter.all": "Semua",
    "portfolio.viewDetails": "Lihat Detail",
    "portfolio.viewProject": "Lihat Proyek",
    "portfolio.liveDemo": "Demo Langsung",
    "portfolio.projectOverview": "Ikhtisar Proyek",
    "portfolio.keyFeatures": "Fitur Utama",
    "portfolio.projectDetails": "Detail Proyek",
    "portfolio.client": "Klien",
    "portfolio.date": "Tanggal",
    "portfolio.technologies": "Teknologi",
    "portfolio.resetFilters": "Reset Filter",
    "portfolio.noProjectsMatch": "Tidak ada proyek yang cocok dengan filter Anda.",
    "portfolio.filterByTags": "Filter berdasarkan tag",
    "portfolio.allTags": "Semua Tag",
    "portfolio.selectTagsToFilter": "Pilih tag untuk menyaring sertifikasi",
    "portfolio.clearFilters": "Hapus filter",
    "portfolio.moreTags": "+{0} lainnya",
    "certifications.title": "Sertifikasi Saya",
    "certifications.subtitle": "Sertifikat profesional dan pencapaian di bidang keamanan siber dan bidang terkait",
    "certifications.viewDetails": "Lihat Detail",
    "certifications.openPdf": "Buka PDF",
    "certifications.description": "Deskripsi",
    "certifications.competencies": "Kompetensi Utama",
    "certifications.competency1": "Memahami prinsip dan praktik terbaik keamanan",
    "certifications.competency2": "Mengidentifikasi dan memitigasi kerentanan keamanan",
    "certifications.competency3": "Mengimplementasikan kontrol dan teknologi keamanan",
    "certifications.competency4": "Menanggapi insiden dan ancaman keamanan",
    "certifications.details": "Detail Sertifikat",
    "certifications.issuedBy": "Dikeluarkan Oleh",
    "certifications.date": "Tanggal Penerbitan",
    "certifications.category": "Kategori",
    "certifications.expertise": "Bidang Keahlian",
    "certifications.searchPlaceholder": "Cari sertifikasi...",
    "certifications.all": "Semua",
    "certifications.noMatch": "Tidak ada sertifikasi yang sesuai dengan filter Anda",
    "certifications.resetFilters": "Reset Filter",
    "certifications.quickLinks": "Tautan Cepat",
    "certifications.latest": "Sertifikat Terbaru",
    "certifications.popular": "Sertifikat Populer",
    "certifications.filterByTags": "Filter berdasarkan tag",
    "certifications.allTags": "Semua Tag",
    "certifications.selectTagsToFilter": "Pilih tag untuk menyaring sertifikasi",
    "certifications.clearFilters": "Hapus filter",
    "certifications.moreTags": "+{0} more",
    "skills.title": "Analisis Keahlian",
    "skills.subtitle": "Visualisasi komprehensif dari keahlian teknis dan pertumbuhan profesional",
    "skills.chart.radarView": "Tampilan Radar",
    "skills.chart.barView": "Tampilan Batang",
    "skills.chart.progressView": "Tampilan Progres",
    "skills.linux": "Admin Linux",
    "skills.linux.description": "Instalasi, konfigurasi, dan manajemen sistem Linux",
    "skills.security": "Keamanan Sistem",
    "skills.security.description": "Implementasi langkah-langkah keamanan dan protokol",
    "skills.virtualization": "Virtualisasi",
    "skills.virtualization.description": "Penyiapan dan pengelolaan lingkungan virtual",
    "skills.scripting": "Shell Scripting",
    "skills.scripting.description": "Otomatisasi tugas melalui skrip shell",
    "skills.documentation": "Dokumentasi",
    "skills.documentation.description": "Pembuatan dokumentasi teknis yang komprehensif",
    "skills.problemSolving": "Pemecahan Masalah",
    "skills.problemSolving.description": "Pendekatan analitis untuk tantangan teknis",
    "skills.development.title": "Pengembangan Profesional",
    "skills.development.description": "Pembelajaran berkelanjutan dan peningkatan keterampilan melalui pelatihan khusus, pengalaman praktis, dan sertifikasi industri. Berkomitmen untuk tetap mengikuti teknologi dan praktik terbaik terbaru di bidang IT dan keamanan siber.",
    "contact.title": "Hubungi Kami",
    "contact.subtitle": "Mari diskusikan bagaimana kami dapat membantu bisnis Anda berkembang",
    "contact.name": "Nama",
    "contact.email": "Email",
    "contact.message": "Pesan",
    "contact.send": "Kirim Pesan",
    "contact.form.title": "Kirim Pesan",
    "contact.form.description": "Isi formulir di bawah ini untuk mengirim pesan via email atau WhatsApp.",
    "contact.form.name": "Nama",
    "contact.form.namePlaceholder": "Nama Anda",
    "contact.form.email": "Email",
    "contact.form.emailPlaceholder": "email@contoh.com",
    "contact.form.subject": "Subjek",
    "contact.form.subjectPlaceholder": "Topik pesan Anda",
    "contact.form.message": "Pesan",
    "contact.form.messagePlaceholder": "Tulis pesan Anda di sini...",
    "contact.form.sending": "Mengirim...",
    "contact.form.whatsapp": "Kirim via WhatsApp",
    "contact.form.emailBtn": "Kirim Langsung",
    "contact.form.emailClient": "Email Client",
    "contact.form.success": "Email Berhasil Terkirim",
    "contact.form.error": "Gagal Mengirim Email",
    "nav.home": "Beranda",
    "nav.services": "Layanan",
    "nav.portfolio": "Portofolio",
    "nav.resume": "Resume",
    "nav.contact": "Kontak",
    "nav.certifications": "Sertifikasi",
    "language.selectLanguage": "Pilih Bahasa",
    "certifications.viewCertificate": "Lihat Sertifikat",
    "certifications.fileDetails": "Informasi File",
    "certifications.quickDetails": "Info Sertifikat",
    "certifications.close": "Tutup",
    "certifications.back": "Kembali",
    "achievements.title": "Pencapaian Profesional",
    "achievements.subtitle": "Hasil terukur dan tonggak penting dari perjalanan profesional saya",
    "achievements.progress": "Progres",
    "achievements.moreDetails": "Detail Lainnya",
    "achievements.lessDetails": "Lebih Sedikit",
    "achievements.keyHighlights": "Poin Utama",
    "achievements.excellence.title": "Keunggulan di Bidang IT",
    "achievements.excellence.value": "5+",
    "achievements.excellence.description": "Tahun pembelajaran berkelanjutan dan pengembangan profesional",
    "achievements.excellence.detail1": "Pembelajaran mandiri tentang administrasi Linux dan keamanan sistem",
    "achievements.excellence.detail2": "Penyelesaian kursus khusus dan lokakarya online",
    "achievements.excellence.detail3": "Penerapan praktis pengetahuan dalam lingkungan profesional",
    "achievements.excellence.detail4": "Peningkatan keterampilan konsisten melalui proyek langsung",
    "achievements.optimization.title": "Optimalisasi Sistem",
    "achievements.optimization.value": "100%",
    "achievements.optimization.description": "Tingkat keberhasilan dalam administrasi sistem dan implementasi keamanan",
    "achievements.optimization.detail1": "Implementasi protokol dan langkah keamanan yang berhasil",
    "achievements.optimization.detail2": "Optimalisasi kinerja sistem dan pemanfaatan sumber daya",
    "achievements.optimization.detail3": "Pemecahan masalah dan resolusi yang efektif",
    "achievements.optimization.detail4": "Pemeliharaan proaktif dan pemantauan sistem",
    "achievements.efficiency.title": "Efisiensi Proses",
    "achievements.efficiency.value": "30%",
    "achievements.efficiency.description": "Peningkatan rata-rata dalam efisiensi operasional untuk klien",
    "achievements.efficiency.detail1": "Efisiensi alur kerja dan proses operasional",
    "achievements.efficiency.detail2": "Implementasi otomatisasi untuk tugas rutin",
    "achievements.efficiency.detail3": "Pengurangan waktu henti sistem dan masalah kinerja",
    "achievements.efficiency.detail4": "Produktivitas yang ditingkatkan melalui infrastruktur IT yang dioptimalkan",
    "achievements.delivery.title": "Pengiriman Proyek",
    "achievements.delivery.value": "100%",
    "achievements.delivery.description": "Tingkat penyelesaian tepat waktu untuk semua proyek yang ditugaskan",
    "achievements.delivery.detail1": "Kepatuhan konsisten terhadap jadwal dan tenggat waktu proyek",
    "achievements.delivery.detail2": "Perencanaan proyek dan alokasi sumber daya yang efektif",
    "achievements.delivery.detail3": "Komunikasi yang jelas dan manajemen pemangku kepentingan",
    "achievements.delivery.detail4": "Jaminan kualitas dan pengujian menyeluruh sebelum pengiriman",
    "growth.title": "Pertumbuhan Profesional Berkelanjutan",
    "growth.description": "Komitmen saya terhadap keunggulan tercermin dalam catatan prestasi dan pertumbuhan yang konsisten. Melalui pembelajaran mandiri yang berdedikasi, aplikasi praktis, dan hasrat terhadap teknologi, saya telah mengembangkan serangkaian keterampilan komprehensif yang memungkinkan saya untuk memberikan hasil yang luar biasa.",
    "growth.lastUpdated": "Terakhir diperbarui: Maret 2025",
    "growth.successRate": "Tingkat Keberhasilan",
    "growth.rateValue": "90%",
    "growth.quickNotes": "Area Fokus Profesional",
    "resume.readyToCollaborate": "Siap Berkolaborasi?",
    "resume.collaborationText": "Saya selalu terbuka untuk membahas proyek baru, peluang, dan kolaborasi.",
    "resume.contactMe": "Hubungi Saya",
    "resume.downloadCV": "Unduh CV",
    "resume.downloading": "Mengunduh...",
    "resume.downloadSuccess": "Berhasil!",
    "resume.downloadSuccessDesc": "CV Anda telah berhasil diunduh",
    "resume.downloadError": "Error",
    "resume.downloadErrorDesc": "Gagal mengunduh CV. Silakan coba lagi nanti."
  },
  // Contoh terjemahan bahasa Spanyol (sebagian)
  es: {
    "hero.title": "Entusiasta de IT & Ciberseguridad",
    "hero.subtitle": "Especializado en Seguridad de Sistemas, Administración Linux y Protección de Redes",
    "hero.cta": "Comenzar",
    "services.title": "Mis Servicios",
    "services.subtitle": "Soluciones integrales adaptadas a sus necesidades",
    "services.uiux.title": "Diseño UI/UX",
    "services.uiux.description": "Experiencias de usuario intuitivas y atractivas que cautivan y convierten.",
    "services.digitalMarketing.title": "Marketing Digital",
    "services.digitalMarketing.description": "Soluciones estratégicas de marketing para impulsar su presencia y alcance en línea.",
    "services.performance.title": "Optimización de Rendimiento",
    "services.performance.description": "Acelere sus plataformas digitales para una mejor experiencia de usuario y SEO.",
    "services.security.title": "Soluciones de Seguridad",
    "services.security.description": "Proteja sus activos digitales con nuestras medidas de seguridad integrales.",
    "portfolio.title": "Mi Portafolio",
    "portfolio.subtitle": "Innovando soluciones avanzadas en la convergencia de IT, sistemas Linux y arquitectura de ciberseguridad - donde la excelencia técnica se encuentra con la innovación visionaria y el crecimiento estratégico",
    "portfolio.technologies": "Tecnologías",
    "skills.title": "Análisis de Habilidades",
    "skills.subtitle": "Visualización integral de experiencia técnica y crecimiento profesional",
    "skills.chart.radarView": "Vista Radar",
    "skills.chart.barView": "Vista de Barras",
    "skills.chart.progressView": "Vista de Progreso",
    "skills.linux": "Admin de Linux",
    "skills.linux.description": "Instalación, configuración y gestión de sistemas Linux",
    "skills.security": "Seguridad de Sistemas",
    "skills.security.description": "Implementación de medidas y protocolos de seguridad",
    "skills.virtualization": "Virtualización",
    "skills.virtualization.description": "Configuración y gestión de entornos virtuales",
    "skills.scripting": "Scripting Shell",
    "skills.scripting.description": "Automatización de tareas mediante scripts shell",
    "skills.documentation": "Documentación",
    "skills.documentation.description": "Creación de documentación técnica completa",
    "skills.problemSolving": "Resolución de Problemas",
    "skills.problemSolving.description": "Enfoque analítico para desafíos técnicos",
    "skills.development.title": "Desarrollo Profesional",
    "skills.development.description": "Aprendizaje continuo y mejora de habilidades a través de formación especializada, experiencia práctica y certificaciones de la industria. Comprometido a mantenerse actualizado con las tecnologías emergentes y las mejores prácticas en TI y ciberseguridad.",
    "nav.home": "Inicio",
    "nav.services": "Servicios",
    "nav.portfolio": "Portafolio",
    "nav.resume": "Currículum",
    "nav.contact": "Contacto",
    "language.selectLanguage": "Seleccionar Idioma",
    "achievements.title": "Logros Profesionales",
    "achievements.subtitle": "Resultados medibles e hitos de mi trayectoria profesional",
    "growth.title": "Crecimiento Profesional Continuo",
    "growth.description": "Mi compromiso con la excelencia se refleja en un historial consistente de logros y crecimiento. A través del aprendizaje autodidacta dedicado, la aplicación práctica y la pasión por la tecnología, he desarrollado un conjunto integral de habilidades que me permite ofrecer resultados excepcionales.",
    "growth.quickNotes": "Áreas de Enfoque Profesional",
    "resume.readyToCollaborate": "¿Listo para Colaborar?",
    "resume.collaborationText": "Siempre estoy abierto a discutir nuevos proyectos, oportunidades y colaboraciones.",
    "resume.contactMe": "Contáctame",
    "resume.downloadCV": "Descargar CV",
    "resume.downloading": "Descargando...",
    "resume.downloadSuccess": "¡Éxito!",
    "resume.downloadSuccessDesc": "Tu CV se ha descargado correctamente",
    "resume.downloadError": "Error",
    "resume.downloadErrorDesc": "Error al descargar el CV. Por favor, inténtalo más tarde."
  },
  fr: {
    "hero.title": "Entusiast de l'IT & la Sécurité Informatique",
    "hero.subtitle": "Spécialisé en Sécurité des Systèmes, Administration Linux et Protection des Réseaux",
    "hero.cta": "Commencer",
    "services.title": "Mes Services",
    "services.subtitle": "Solutions intégrales adaptées à vos besoins",
    "services.uiux.title": "Conception UI/UX",
    "services.uiux.description": "Expériences utilisateur intuitives et attractives qui captivent et convertissent.",
    "services.digitalMarketing.title": "Marketing Numérique",
    "services.digitalMarketing.description": "Solutions stratégiques de marketing pour renforcer votre présence et votre portée en ligne.",
    "services.performance.title": "Optimisation de la Performance",
    "services.performance.description": "Accélérez vos plateformes numériques pour une meilleure expérience utilisateur et SEO.",
    "services.security.title": "Solutions de Sécurité",
    "services.security.description": "Protégez vos actifs numériques avec nos mesures de sécurité intégrales.",
    "portfolio.title": "Mon Portefeuille",
    "portfolio.subtitle": "Innovant des solutions avancées à la convergence de l'IT, des systèmes Linux et de l'architecture de la sécurité informatique - où l'excellence technique rencontre l'innovation visionnaire et le croissance stratégique",
    "portfolio.technologies": "Technologies",
    "skills.title": "Analyse des Compétences",
    "skills.subtitle": "Visualisation intégrale de l'expérience technique et de croissance professionnelle",
    "skills.chart.radarView": "Vue Radar",
    "skills.chart.barView": "Vue en Barres",
    "skills.chart.progressView": "Vue de Progression",
    "skills.linux": "Admin de Linux",
    "skills.linux.description": "Installation, configuration et gestion des systèmes Linux",
    "skills.security": "Sécurité des Systèmes",
    "skills.security.description": "Mise en œuvre des mesures et des protocoles de sécurité",
    "skills.virtualization": "Virtualisation",
    "skills.virtualization.description": "Configuration et gestion des environnements virtuels",
    "skills.scripting": "Scripting Shell",
    "skills.scripting.description": "Automatisation des tâches par le biais de scripts shell",
    "skills.documentation": "Documentation",
    "skills.documentation.description": "Création de documentation technique complète",
    "skills.problemSolving": "Résolution de Problèmes",
    "skills.problemSolving.description": "Approche analytique pour les défis techniques",
    "skills.development.title": "Développement Professionnel",
    "skills.development.description": "Apprentissage continu et amélioration des compétences grâce à la formation spécialisée, l'expérience pratique et les certifications de l'industrie. Engagé à rester à jour avec les technologies émergentes et les meilleures pratiques en TI et en sécurité informatique.",
    "nav.home": "Accueil",
    "nav.services": "Services",
    "nav.portfolio": "Portefeuille",
    "nav.resume": "Curriculum",
    "nav.contact": "Contact",
    "language.selectLanguage": "Sélectionner Langue",
    "achievements.title": "Réalisations Professionnelles",
    "achievements.subtitle": "Résultats mesurables et jalons de mon parcours professionnel",
    "growth.title": "Croissance Professionnelle Continue",
    "growth.description": "Mon engagement envers l'excellence se reflète dans un bilan constant de réussite et de croissance. Grâce à l'apprentissage autonome dévoué, à l'application pratique et à la passion pour la technologie, j'ai développé un ensemble complet de compétences qui me permettent de fournir des résultats exceptionnels.",
    "growth.quickNotes": "Domaines d'Intérêt Professionnels",
    "resume.readyToCollaborate": "Prêt à Collaborer?",
    "resume.collaborationText": "Je suis toujours ouvert à discuter de nouveaux projets, opportunités et collaborations.",
    "resume.contactMe": "Contactez-moi",
    "resume.downloadCV": "Télécharger CV",
    "resume.downloading": "Téléchargement...",
    "resume.downloadSuccess": "Succès!",
    "resume.downloadSuccessDesc": "Votre CV a été téléchargé avec succès",
    "resume.downloadError": "Erreur",
    "resume.downloadErrorDesc": "Échec du téléchargement du CV. Veuillez réessayer plus tard."
  },
  de: {
    "resume.readyToCollaborate": "Bereit zur Zusammenarbeit?",
    "resume.collaborationText": "Ich bin immer offen für die Diskussion neuer Projekte, Möglichkeiten und Zusammenarbeiten.",
    "resume.contactMe": "Kontaktieren Sie mich",
    "resume.downloadCV": "Lebenslauf herunterladen",
    "resume.downloading": "Wird heruntergeladen...",
    "resume.downloadSuccess": "Erfolg!",
    "resume.downloadSuccessDesc": "Ihr Lebenslauf wurde erfolgreich heruntergeladen",
    "resume.downloadError": "Fehler",
    "resume.downloadErrorDesc": "Lebenslauf konnte nicht heruntergeladen werden. Bitte versuchen Sie es später erneut."
  },
  zh: {
    "resume.readyToCollaborate": "准备合作？",
    "resume.collaborationText": "我始终愿意讨论新项目、机会和合作。",
    "resume.contactMe": "联系我",
    "resume.downloadCV": "下载简历",
    "resume.downloading": "下载中...",
    "resume.downloadSuccess": "成功！",
    "resume.downloadSuccessDesc": "您的简历已成功下载",
    "resume.downloadError": "错误",
    "resume.downloadErrorDesc": "下载简历失败。请稍后再试。"
  },
  ja: {
    "resume.readyToCollaborate": "協力する準備はできていますか？",
    "resume.collaborationText": "新しいプロジェクト、機会、コラボレーションについて話し合うことはいつでも歓迎します。",
    "resume.contactMe": "お問い合わせ",
    "resume.downloadCV": "履歴書をダウンロード",
    "resume.downloading": "ダウンロード中...",
    "resume.downloadSuccess": "成功！",
    "resume.downloadSuccessDesc": "履歴書が正常にダウンロードされました",
    "resume.downloadError": "エラー",
    "resume.downloadErrorDesc": "履歴書のダウンロードに失敗しました。後でもう一度お試しください。"
  },
  ko: {
    "resume.readyToCollaborate": "협업할 준비가 되셨나요?",
    "resume.collaborationText": "저는 항상 새로운 프로젝트, 기회 및 협업에 대해 논의하는 것을 환영합니다.",
    "resume.contactMe": "문의하기",
    "resume.downloadCV": "이력서 다운로드",
    "resume.downloading": "다운로드 중...",
    "resume.downloadSuccess": "성공!",
    "resume.downloadSuccessDesc": "이력서가 성공적으로 다운로드되었습니다",
    "resume.downloadError": "오류",
    "resume.downloadErrorDesc": "이력서 다운로드에 실패했습니다. 나중에 다시 시도해 주세요."
  },
  ar: {
    "resume.readyToCollaborate": "هل أنت مستعد للتعاون؟",
    "resume.collaborationText": "أنا دائما منفتح لمناقشة المشاريع الجديدة والفرص والتعاون.",
    "resume.contactMe": "اتصل بي",
    "resume.downloadCV": "تحميل السيرة الذاتية",
    "resume.downloading": "جاري التحميل...",
    "resume.downloadSuccess": "نجاح!",
    "resume.downloadSuccessDesc": "تم تنزيل سيرتك الذاتية بنجاح",
    "resume.downloadError": "خطأ",
    "resume.downloadErrorDesc": "فشل تنزيل السيرة الذاتية. يرجى المحاولة مرة أخرى لاحقًا."
  }
}

// Gabungkan terjemahan dari berbagai sumber
const translations: TranslationsType = mergeTranslations(baseTranslations, additionalTranslations)

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Menyimpan preferensi bahasa di localStorage
  const [language, setLanguage] = useState<Language>("en")
  const [mounted, setMounted] = useState(false)

  // Set mounted state setelah hydration dan ambil preferensi bahasa dari localStorage
  useEffect(() => {
    setMounted(true)
    
    // Ambil preferensi bahasa dari localStorage jika ada
    const savedLanguage = localStorage.getItem("selectedLanguage") as Language
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguage(savedLanguage)
    } else {
      // Deteksi bahasa browser sebagai fallback
      const browserLanguage = navigator.language.split('-')[0] as Language
      if (Object.keys(translations).includes(browserLanguage)) {
        setLanguage(browserLanguage)
      }
    }
  }, [])

  // Fungsi untuk mengganti bahasa dan menyimpannya ke localStorage
  const changeLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("selectedLanguage", lang)
  }

  // Fungsi untuk mendapatkan daftar semua bahasa yang tersedia
  const getAllLanguages = () => {
    return Object.keys(translations).map((code) => ({
      code: code as Language,
      name: languageNames[code as Language] || code
    }))
  }

  // Fungsi untuk menerjemahkan teks dengan fallback yang lebih baik
  const t = (key: string) => {
    // Cek apakah kunci ada di terjemahan bahasa yang dipilih
    if (translations[language]?.[key as TranslationKeys]) {
      return translations[language]![key as TranslationKeys]!
    }
    
    // Fallback ke bahasa Inggris jika tidak ditemukan
    if (translations.en?.[key as TranslationKeys]) {
      return translations.en[key as TranslationKeys]!
    }
    
    // Jika tidak ditemukan sama sekali, kembalikan kunci asli
    return key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, mounted, getAllLanguages, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

